#!/bin/bash
# sam package \
#     --template-file template.yaml \
#     --output-template-file packaged.yaml \
#     --s3-bucket sam-packages-one

sam build \
    --use-container

#     --template-file packaged.yaml \
sam deploy \
    --stack-name aws-sam-two \
    --capabilities CAPABILITY_IAM \
    --region us-east-1 \
    --s3-bucket sam-packages-one
