AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: SAM app that uses validated and filters data uploaded to S3

Resources:
  DataValidatorAndUploader:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Validates and filters data uploaded to S3
      MemorySize: 512
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceImageBucket
            Events:
              - 's3:ObjectCreated:*'
  
  SourceImageBucket:
    Type: 'AWS::S3::Bucket'
