AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: SAM app that validates and uploads data back to S3 prefix

Parameters:
  AccountName:
    Type: String
    Default: '{{resolve:ssm/account-name:1}}'
  ReadPrefix:
    Type: String
    Default: model-data
  WritePrefix:
    Type: String
    Default: validated-model-data
  FileExtension:
    Type: String
    Default: .csv
  BucketNamePrefix:
    Type: String
    Default: sam-test-foo-is
  TempName:
    Type: String
    Default: bar

Resources:
  DataValidatorAndUploader:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 900
      MemorySize: 1024
      Description: Validates and uploads data to S3 prefix
      Environment:
        Variables:
          accountName:
            Ref: AccountName
          readPrefix:
            Ref: ReadPrefix
          writePrefix:
            Ref: WritePrefix
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
              Resource: !Join ['', ['arn:aws:s3:::', !Ref BucketNamePrefix, !Ref TempName, '/*']]
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: S3Bucket
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value:
                      Ref: ReadPrefix
                  - Name: suffix
                    Value:
                      Ref: FileExtension
  
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', [!Ref BucketNamePrefix, !Ref TempName]]

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the Amazon S3 bucket which stores the data
